{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-data-jpa",
    "version": "3.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.4.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-jdbc",
          "version": {
            "requires": "3.4.4"
          }
        },
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-core",
          "version": {
            "requires": "6.6.11.Final"
          }
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-jpa",
          "version": {
            "requires": "3.4.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aspects",
          "version": {
            "requires": "6.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-3.4.4.jar",
          "url": "spring-boot-starter-data-jpa-3.4.4.jar",
          "size": 4762,
          "sha512": "328fabb64861b35e5f125f84ed7c4dce2771a7311451983e746badfb6ab47368f346afef3718ef8a441ea89f95d60f36d28cd65ca98400eea2fbb11b48312131",
          "sha256": "b24040549e3c2515961894de51a2fd2aac3ffc31929830e70e4340be9bf64dbc",
          "sha1": "7e0ab04a0aa460295c7a2e485c7809a733469824",
          "md5": "006c851c376130c94773a08aa6691e54"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.4.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-jdbc",
          "version": {
            "requires": "3.4.4"
          }
        },
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-core",
          "version": {
            "requires": "6.6.11.Final"
          }
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-jpa",
          "version": {
            "requires": "3.4.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aspects",
          "version": {
            "requires": "6.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-3.4.4.jar",
          "url": "spring-boot-starter-data-jpa-3.4.4.jar",
          "size": 4762,
          "sha512": "328fabb64861b35e5f125f84ed7c4dce2771a7311451983e746badfb6ab47368f346afef3718ef8a441ea89f95d60f36d28cd65ca98400eea2fbb11b48312131",
          "sha256": "b24040549e3c2515961894de51a2fd2aac3ffc31929830e70e4340be9bf64dbc",
          "sha1": "7e0ab04a0aa460295c7a2e485c7809a733469824",
          "md5": "006c851c376130c94773a08aa6691e54"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-3.4.4-javadoc.jar",
          "url": "spring-boot-starter-data-jpa-3.4.4-javadoc.jar",
          "size": 4762,
          "sha512": "328fabb64861b35e5f125f84ed7c4dce2771a7311451983e746badfb6ab47368f346afef3718ef8a441ea89f95d60f36d28cd65ca98400eea2fbb11b48312131",
          "sha256": "b24040549e3c2515961894de51a2fd2aac3ffc31929830e70e4340be9bf64dbc",
          "sha1": "7e0ab04a0aa460295c7a2e485c7809a733469824",
          "md5": "006c851c376130c94773a08aa6691e54"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-3.4.4-sources.jar",
          "url": "spring-boot-starter-data-jpa-3.4.4-sources.jar",
          "size": 4762,
          "sha512": "328fabb64861b35e5f125f84ed7c4dce2771a7311451983e746badfb6ab47368f346afef3718ef8a441ea89f95d60f36d28cd65ca98400eea2fbb11b48312131",
          "sha256": "b24040549e3c2515961894de51a2fd2aac3ffc31929830e70e4340be9bf64dbc",
          "sha1": "7e0ab04a0aa460295c7a2e485c7809a733469824",
          "md5": "006c851c376130c94773a08aa6691e54"
        }
      ]
    }
  ]
}
