{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-jdbc",
    "version": "3.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.4.4"
          }
        },
        {
          "group": "com.zaxxer",
          "module": "HikariCP",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-jdbc",
          "version": {
            "requires": "6.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-jdbc-3.4.4.jar",
          "url": "spring-boot-starter-jdbc-3.4.4.jar",
          "size": 4770,
          "sha512": "0828b67496f4dc25e04cbdae0ae4c06bdd9b537e64a3d9efc4d72bf919ea2601bebb3e2e6a0a0a70bd7dabafe3342cf3f6db4637aca5d0588750d4aa81f02920",
          "sha256": "170abba02cb4b7d5bbda965872d54d587ec1fa7cd0494337ba6a29440b744e58",
          "sha1": "c1059487b20babd2e0552d285d64d3cb655d0c4d",
          "md5": "c65bf566e59a559ac8810f3ae3170d88"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.4.4"
          }
        },
        {
          "group": "com.zaxxer",
          "module": "HikariCP",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-jdbc",
          "version": {
            "requires": "6.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-jdbc-3.4.4.jar",
          "url": "spring-boot-starter-jdbc-3.4.4.jar",
          "size": 4770,
          "sha512": "0828b67496f4dc25e04cbdae0ae4c06bdd9b537e64a3d9efc4d72bf919ea2601bebb3e2e6a0a0a70bd7dabafe3342cf3f6db4637aca5d0588750d4aa81f02920",
          "sha256": "170abba02cb4b7d5bbda965872d54d587ec1fa7cd0494337ba6a29440b744e58",
          "sha1": "c1059487b20babd2e0552d285d64d3cb655d0c4d",
          "md5": "c65bf566e59a559ac8810f3ae3170d88"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-jdbc-3.4.4-javadoc.jar",
          "url": "spring-boot-starter-jdbc-3.4.4-javadoc.jar",
          "size": 4770,
          "sha512": "96666d8d8fff68c208dd82769ecd3553a22496b53efd92e9ffea7f4d1a3f13c5a2915fcedc87b6cc18acdb35d5c8b13435fb89bb5aee19ce4fd2a014536c9af5",
          "sha256": "5563d6fe5ccd079845b230bb1953b4e8a2f32dc72533bd7dbe64d1a3c31e6060",
          "sha1": "b5d904fa4f426baa1dac0ac26c074ccd1ec19cf2",
          "md5": "2ed2fb9ca0e68fd8e9cec2ecafc07a77"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-jdbc-3.4.4-sources.jar",
          "url": "spring-boot-starter-jdbc-3.4.4-sources.jar",
          "size": 4770,
          "sha512": "96666d8d8fff68c208dd82769ecd3553a22496b53efd92e9ffea7f4d1a3f13c5a2915fcedc87b6cc18acdb35d5c8b13435fb89bb5aee19ce4fd2a014536c9af5",
          "sha256": "5563d6fe5ccd079845b230bb1953b4e8a2f32dc72533bd7dbe64d1a3c31e6060",
          "sha1": "b5d904fa4f426baa1dac0ac26c074ccd1ec19cf2",
          "md5": "2ed2fb9ca0e68fd8e9cec2ecafc07a77"
        }
      ]
    }
  ]
}
