{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.security",
    "module": "spring-security-config",
    "version": "6.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "6.4.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.2.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.2.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.4"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-config-6.4.4.jar",
          "url": "spring-security-config-6.4.4.jar",
          "size": 2024913,
          "sha512": "07d5100c1aeaf02f7fe1fb1e22fa03b0325b4e6e57a20c946a0afaae0f66f34ba5087cf5ab9c2e110e938c3215595ef07bccaafd5b266a4ce057847fc3428f25",
          "sha256": "f13f2365b4af41b33e40af657014db773de858d84c74f34c9ada471c96f9c169",
          "sha1": "2bb5d949fc3b935a88c701555fdc3af3d0381228",
          "md5": "a5e512bf1bc007132d8f38001ab26128"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "6.4.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.2.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.2.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.4"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-config-6.4.4.jar",
          "url": "spring-security-config-6.4.4.jar",
          "size": 2024913,
          "sha512": "07d5100c1aeaf02f7fe1fb1e22fa03b0325b4e6e57a20c946a0afaae0f66f34ba5087cf5ab9c2e110e938c3215595ef07bccaafd5b266a4ce057847fc3428f25",
          "sha256": "f13f2365b4af41b33e40af657014db773de858d84c74f34c9ada471c96f9c169",
          "sha1": "2bb5d949fc3b935a88c701555fdc3af3d0381228",
          "md5": "a5e512bf1bc007132d8f38001ab26128"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-config-6.4.4-javadoc.jar",
          "url": "spring-security-config-6.4.4-javadoc.jar",
          "size": 1171650,
          "sha512": "34e7a5e1b31339b010c760c44bc200cd0c799f5934352f95bc540c601dda5fb2ad71673e88f0ce7d4130a2d325c97254521773560f511f9054e25fcf4d04b062",
          "sha256": "0bbb5c2bcc0c7da76c0bb07822a1d8a39f3615c3c882a00a9494cacf917860a0",
          "sha1": "f50082ea913d78b2455c6ccefce832c4c3db6f7c",
          "md5": "f126618f1a9580207d39616824391188"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-config-6.4.4-sources.jar",
          "url": "spring-security-config-6.4.4-sources.jar",
          "size": 1384431,
          "sha512": "37930fe396c4614f78fe92a3ed8a81cf262dce0bc6b09276c829ecc27a29791a7a58df1a400853ddadf09149c7ba16e3e0bc5335511a16ac98681f88f2e90344",
          "sha256": "4b6340bc8afccb5b313383ac9a7bd60e5aacf6b9f5aa5470f97ab1ce47660912",
          "sha1": "55be5a26710d95b857130d09f547ea6bf99cdbf8",
          "md5": "6957c761a747d8c121268b1653590fe6"
        },
        {
          "name": "spring-security-config-6.4.4-sources.jar",
          "url": "spring-security-config-6.4.4-sources.jar",
          "size": 1384431,
          "sha512": "37930fe396c4614f78fe92a3ed8a81cf262dce0bc6b09276c829ecc27a29791a7a58df1a400853ddadf09149c7ba16e3e0bc5335511a16ac98681f88f2e90344",
          "sha256": "4b6340bc8afccb5b313383ac9a7bd60e5aacf6b9f5aa5470f97ab1ce47660912",
          "sha1": "55be5a26710d95b857130d09f547ea6bf99cdbf8",
          "md5": "6957c761a747d8c121268b1653590fe6"
        }
      ]
    }
  ]
}
