spring:
  datasource:
    url: ${LOCAL_MYSQL_URL:jdbc:mysql://localhost:3306/backend?serverTimezone=Asia/Seoul&characterEncoding=UTF-8}
    username: ${LOCAL_MYSQL_USERNAME:root}
    password: ${LOCAL_MYSQL_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: ${LOCAL_REDIS_HOST:localhost}
      port: ${LOCAL_REDIS_PORT:6379}
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql,classpath:data-local.sql

server:
  port: ${LOCAL_SERVER_PORT:8080}
