spring:
  datasource:
    url: ${DEV_MYSQL_URL:${MYSQL_URL:jdbc:mysql://localhost:3306/backend?serverTimezone=Asia/Seoul&characterEncoding=UTF-8}}
    username: ${DEV_MYSQL_USERNAME:${MYSQL_USERNAME:root}}
    password: ${DEV_MYSQL_PASSWORD:${MYSQL_PASSWORD:1234}}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: ${DEV_REDIS_HOST:${REDIS_HOST:localhost}}
      port: ${DEV_REDIS_PORT:${REDIS_PORT:6379}}
  sql:
    init:
      mode: never

server:
  port: ${DEV_SERVER_PORT:${SERVER_PORT:8080}}
