{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-oxm",
    "version": "6.2.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-oxm-6.2.5.jar",
          "url": "spring-oxm-6.2.5.jar",
          "size": 60041,
          "sha512": "d82455596bafa65df576443ae08a249687adc9d28e83c014a47e8b73453888b44541df14b46151474a67aaaff85ba4ba884ead1b81c37fcabdaea5964cc725f6",
          "sha256": "3188046ecda5432d8d2a5beec6d96840be990353db3f3e674ce61aa6a501df17",
          "sha1": "5c561804b5a2903efefd875d3b940595126a3172",
          "md5": "95fe48ddf8228781907d896ab77ce74b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-oxm-6.2.5.jar",
          "url": "spring-oxm-6.2.5.jar",
          "size": 60041,
          "sha512": "d82455596bafa65df576443ae08a249687adc9d28e83c014a47e8b73453888b44541df14b46151474a67aaaff85ba4ba884ead1b81c37fcabdaea5964cc725f6",
          "sha256": "3188046ecda5432d8d2a5beec6d96840be990353db3f3e674ce61aa6a501df17",
          "sha1": "5c561804b5a2903efefd875d3b940595126a3172",
          "md5": "95fe48ddf8228781907d896ab77ce74b"
        }
      ]
    }
  ]
}
