{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-validation",
    "version": "3.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.4.4"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "10.1.39"
          }
        },
        {
          "group": "org.hibernate.validator",
          "module": "hibernate-validator",
          "version": {
            "requires": "8.0.2.Final"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-validation-3.4.4.jar",
          "url": "spring-boot-starter-validation-3.4.4.jar",
          "size": 4768,
          "sha512": "aa05a9d42286955f32ce30d3f2b761e2b0e86af95e4434ec5b6cf86f7c50a6557d66e2124109ffa8adae087c2a248900c7437fc0c1fc2a709aa9a1dcef304b2a",
          "sha256": "3fbd177ad6379cfb64b487dd4c281b6578524e89973e961edb53cca9a7e25f14",
          "sha1": "0fa0bc381ac02704bb56631c13e33c3be437aa5c",
          "md5": "0dd49824534010839016e29fbc256b65"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.4.4"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "10.1.39"
          }
        },
        {
          "group": "org.hibernate.validator",
          "module": "hibernate-validator",
          "version": {
            "requires": "8.0.2.Final"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-validation-3.4.4.jar",
          "url": "spring-boot-starter-validation-3.4.4.jar",
          "size": 4768,
          "sha512": "aa05a9d42286955f32ce30d3f2b761e2b0e86af95e4434ec5b6cf86f7c50a6557d66e2124109ffa8adae087c2a248900c7437fc0c1fc2a709aa9a1dcef304b2a",
          "sha256": "3fbd177ad6379cfb64b487dd4c281b6578524e89973e961edb53cca9a7e25f14",
          "sha1": "0fa0bc381ac02704bb56631c13e33c3be437aa5c",
          "md5": "0dd49824534010839016e29fbc256b65"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-validation-3.4.4-javadoc.jar",
          "url": "spring-boot-starter-validation-3.4.4-javadoc.jar",
          "size": 4768,
          "sha512": "56888b7ce8c7e9ac7b04ddd3a81a651304e22e4ccb4e8d774b2ab8ab2522e355516360f4a0411d131e9a1921dd032e45dacbffb611d1665bca3b8c17c686d6d6",
          "sha256": "23766e373d81aae88d72d9433eb659564a202c72e8fb3e0d1089821af66bfd4a",
          "sha1": "7595db0ba866401a0356fb0128b1dda86f2188dd",
          "md5": "40f78a7da98ba621acecd618dff5b386"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-validation-3.4.4-sources.jar",
          "url": "spring-boot-starter-validation-3.4.4-sources.jar",
          "size": 4768,
          "sha512": "56888b7ce8c7e9ac7b04ddd3a81a651304e22e4ccb4e8d774b2ab8ab2522e355516360f4a0411d131e9a1921dd032e45dacbffb611d1665bca3b8c17c686d6d6",
          "sha256": "23766e373d81aae88d72d9433eb659564a202c72e8fb3e0d1089821af66bfd4a",
          "sha1": "7595db0ba866401a0356fb0128b1dda86f2188dd",
          "md5": "40f78a7da98ba621acecd618dff5b386"
        }
      ]
    }
  ]
}
