{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-data-redis",
    "version": "3.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.4.4"
          }
        },
        {
          "group": "io.lettuce",
          "module": "lettuce-core",
          "version": {
            "requires": "6.4.2.RELEASE"
          }
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-redis",
          "version": {
            "requires": "3.4.4"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-data-redis-3.4.4.jar",
          "url": "spring-boot-starter-data-redis-3.4.4.jar",
          "size": 4785,
          "sha512": "53b2c47e467f9566165db5d0d6456d1696b0ef883458ae7709f565a7e2042638b2c300cc206c342f1cf7281a9dd3e949cd2734720580fdc4dce724d5dadb1b5a",
          "sha256": "6f936b6e38a1969dfdae9ac1e163908a5a970392abd66c8a13be77fc531c4602",
          "sha1": "edcb05561bf12e4b9e7bb113ef22347af54018dc",
          "md5": "d0d4f61b6060ee2c37d3c296ebd38721"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.4.4"
          }
        },
        {
          "group": "io.lettuce",
          "module": "lettuce-core",
          "version": {
            "requires": "6.4.2.RELEASE"
          }
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-redis",
          "version": {
            "requires": "3.4.4"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-data-redis-3.4.4.jar",
          "url": "spring-boot-starter-data-redis-3.4.4.jar",
          "size": 4785,
          "sha512": "53b2c47e467f9566165db5d0d6456d1696b0ef883458ae7709f565a7e2042638b2c300cc206c342f1cf7281a9dd3e949cd2734720580fdc4dce724d5dadb1b5a",
          "sha256": "6f936b6e38a1969dfdae9ac1e163908a5a970392abd66c8a13be77fc531c4602",
          "sha1": "edcb05561bf12e4b9e7bb113ef22347af54018dc",
          "md5": "d0d4f61b6060ee2c37d3c296ebd38721"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-redis-3.4.4-javadoc.jar",
          "url": "spring-boot-starter-data-redis-3.4.4-javadoc.jar",
          "size": 4785,
          "sha512": "53b2c47e467f9566165db5d0d6456d1696b0ef883458ae7709f565a7e2042638b2c300cc206c342f1cf7281a9dd3e949cd2734720580fdc4dce724d5dadb1b5a",
          "sha256": "6f936b6e38a1969dfdae9ac1e163908a5a970392abd66c8a13be77fc531c4602",
          "sha1": "edcb05561bf12e4b9e7bb113ef22347af54018dc",
          "md5": "d0d4f61b6060ee2c37d3c296ebd38721"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-redis-3.4.4-sources.jar",
          "url": "spring-boot-starter-data-redis-3.4.4-sources.jar",
          "size": 4785,
          "sha512": "53b2c47e467f9566165db5d0d6456d1696b0ef883458ae7709f565a7e2042638b2c300cc206c342f1cf7281a9dd3e949cd2734720580fdc4dce724d5dadb1b5a",
          "sha256": "6f936b6e38a1969dfdae9ac1e163908a5a970392abd66c8a13be77fc531c4602",
          "sha1": "edcb05561bf12e4b9e7bb113ef22347af54018dc",
          "md5": "d0d4f61b6060ee2c37d3c296ebd38721"
        }
      ]
    }
  ]
}
