{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-orm",
    "version": "6.2.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-jdbc",
          "version": {
            "requires": "6.2.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "6.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-orm-6.2.5.jar",
          "url": "spring-orm-6.2.5.jar",
          "size": 234786,
          "sha512": "6be7fd44d0cf1a95bd1f45cfaab105db7e4b810faba3db5e83a33cb441e9c155451ff213fcab8cb716f57d656bd3f4e8f609793523f2e86c3dfe697a485631e2",
          "sha256": "08c54c22eb0222184e06fbead6a8c20709a9b1f94d618258245fe01efb60244b",
          "sha1": "00b2edc79b16b9cad32666dfdc8cc92896429b9c",
          "md5": "c1359d3f58f78b41378b6625c8150272"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-jdbc",
          "version": {
            "requires": "6.2.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "6.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-orm-6.2.5.jar",
          "url": "spring-orm-6.2.5.jar",
          "size": 234786,
          "sha512": "6be7fd44d0cf1a95bd1f45cfaab105db7e4b810faba3db5e83a33cb441e9c155451ff213fcab8cb716f57d656bd3f4e8f609793523f2e86c3dfe697a485631e2",
          "sha256": "08c54c22eb0222184e06fbead6a8c20709a9b1f94d618258245fe01efb60244b",
          "sha1": "00b2edc79b16b9cad32666dfdc8cc92896429b9c",
          "md5": "c1359d3f58f78b41378b6625c8150272"
        }
      ]
    }
  ]
}
