{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-security",
    "version": "3.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.4.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.2.5"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-config",
          "version": {
            "requires": "6.4.4"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-web",
          "version": {
            "requires": "6.4.4"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-security-3.4.4.jar",
          "url": "spring-boot-starter-security-3.4.4.jar",
          "size": 4743,
          "sha512": "801ee86a1bce3cba47d67f0f943afcab32163028954fb26801e6094a002af87b2a45d31f137c9ee537a4a462432703e28bc87e726675896c1d2936b69ab9dc34",
          "sha256": "796452c20a9a0b46ed721d6f32fd35daf84074e8e345cec8318ad1217d08e7f1",
          "sha1": "796c83e0f08979c87b62d19d7d956d1ea453f4cd",
          "md5": "bfc00a0a0dbfdc36ed8584c9c906f321"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.4.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.2.5"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-config",
          "version": {
            "requires": "6.4.4"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-web",
          "version": {
            "requires": "6.4.4"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-security-3.4.4.jar",
          "url": "spring-boot-starter-security-3.4.4.jar",
          "size": 4743,
          "sha512": "801ee86a1bce3cba47d67f0f943afcab32163028954fb26801e6094a002af87b2a45d31f137c9ee537a4a462432703e28bc87e726675896c1d2936b69ab9dc34",
          "sha256": "796452c20a9a0b46ed721d6f32fd35daf84074e8e345cec8318ad1217d08e7f1",
          "sha1": "796c83e0f08979c87b62d19d7d956d1ea453f4cd",
          "md5": "bfc00a0a0dbfdc36ed8584c9c906f321"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-security-3.4.4-javadoc.jar",
          "url": "spring-boot-starter-security-3.4.4-javadoc.jar",
          "size": 4743,
          "sha512": "801ee86a1bce3cba47d67f0f943afcab32163028954fb26801e6094a002af87b2a45d31f137c9ee537a4a462432703e28bc87e726675896c1d2936b69ab9dc34",
          "sha256": "796452c20a9a0b46ed721d6f32fd35daf84074e8e345cec8318ad1217d08e7f1",
          "sha1": "796c83e0f08979c87b62d19d7d956d1ea453f4cd",
          "md5": "bfc00a0a0dbfdc36ed8584c9c906f321"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-security-3.4.4-sources.jar",
          "url": "spring-boot-starter-security-3.4.4-sources.jar",
          "size": 4743,
          "sha512": "801ee86a1bce3cba47d67f0f943afcab32163028954fb26801e6094a002af87b2a45d31f137c9ee537a4a462432703e28bc87e726675896c1d2936b69ab9dc34",
          "sha256": "796452c20a9a0b46ed721d6f32fd35daf84074e8e345cec8318ad1217d08e7f1",
          "sha1": "796c83e0f08979c87b62d19d7d956d1ea453f4cd",
          "md5": "bfc00a0a0dbfdc36ed8584c9c906f321"
        }
      ]
    }
  ]
}
