{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-context-support",
    "version": "6.2.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.2.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-context-support-6.2.5.jar",
          "url": "spring-context-support-6.2.5.jar",
          "size": 175199,
          "sha512": "872049c28698a8d872421ebeba33fb9f733e793387cadbb8f749a852784dbb28c8d3e2b24cde29eb9cd001046cf9d22234786acba4447a50111c71a1b156a76d",
          "sha256": "93f2de3b6236dd82ea52f3f184c1c3bd49496162d87f06ddbc426058905fcda7",
          "sha1": "a084213d1f07c916e6bc3ff016eb9d3022a4da5c",
          "md5": "121dd8af30e0c6185e8020c8fb69f951"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.2.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-context-support-6.2.5.jar",
          "url": "spring-context-support-6.2.5.jar",
          "size": 175199,
          "sha512": "872049c28698a8d872421ebeba33fb9f733e793387cadbb8f749a852784dbb28c8d3e2b24cde29eb9cd001046cf9d22234786acba4447a50111c71a1b156a76d",
          "sha256": "93f2de3b6236dd82ea52f3f184c1c3bd49496162d87f06ddbc426058905fcda7",
          "sha1": "a084213d1f07c916e6bc3ff016eb9d3022a4da5c",
          "md5": "121dd8af30e0c6185e8020c8fb69f951"
        }
      ]
    }
  ]
}
