{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-tx",
    "version": "6.2.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-tx-6.2.5.jar",
          "url": "spring-tx-6.2.5.jar",
          "size": 285367,
          "sha512": "7a30fc4936bb7a00a48f3edc881af7276a624a1cefb09322da271d009be6d2a1ae8f6e6eec2e5fe16f26adb4ff22435e40a7ee110f193e409f8d1e7dc9911d1e",
          "sha256": "a0fc4f275e04cf1b31dde8b5348e10ed03372cd734c6e3d14e0863263794a9e0",
          "sha1": "99ecc1c976f58ad63df7205e18eac628f2f1fa9a",
          "md5": "702e6a86635e37699590d31041364260"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-tx-6.2.5.jar",
          "url": "spring-tx-6.2.5.jar",
          "size": 285367,
          "sha512": "7a30fc4936bb7a00a48f3edc881af7276a624a1cefb09322da271d009be6d2a1ae8f6e6eec2e5fe16f26adb4ff22435e40a7ee110f193e409f8d1e7dc9911d1e",
          "sha256": "a0fc4f275e04cf1b31dde8b5348e10ed03372cd734c6e3d14e0863263794a9e0",
          "sha1": "99ecc1c976f58ad63df7205e18eac628f2f1fa9a",
          "md5": "702e6a86635e37699590d31041364260"
        }
      ]
    }
  ]
}
