{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.security",
    "module": "spring-security-web",
    "version": "6.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "6.4.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.2.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.2.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "6.2.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.2.4"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-web-6.4.4.jar",
          "url": "spring-security-web-6.4.4.jar",
          "size": 996920,
          "sha512": "94d37502956b0104493c7d06ad60c1cd6c9b308e444e07751ad020ade59e14918293f008b57538d6d0dd58763928b64bd5def9ddeeb460679934127b213fec41",
          "sha256": "7705eec34c86607d3e2c81965d20584fa46819baf311aa3e9381deebbeceb9a4",
          "sha1": "b33b3eba22ef5242caef0cf3c0575b0cc303519b",
          "md5": "546dc3133591adea67e7c4b9f1242d0e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "6.4.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.2.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.2.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "6.2.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.2.4"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-web-6.4.4.jar",
          "url": "spring-security-web-6.4.4.jar",
          "size": 996920,
          "sha512": "94d37502956b0104493c7d06ad60c1cd6c9b308e444e07751ad020ade59e14918293f008b57538d6d0dd58763928b64bd5def9ddeeb460679934127b213fec41",
          "sha256": "7705eec34c86607d3e2c81965d20584fa46819baf311aa3e9381deebbeceb9a4",
          "sha1": "b33b3eba22ef5242caef0cf3c0575b0cc303519b",
          "md5": "546dc3133591adea67e7c4b9f1242d0e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-web-6.4.4-javadoc.jar",
          "url": "spring-security-web-6.4.4-javadoc.jar",
          "size": 2222490,
          "sha512": "bd84e1331cd51ec611d32205f46a11993202b300e8d99f9343c6c876db5aa1a9a6d62ed46059a1c74a5c30933564a213e6aadf84a3f84a59892b8d544f9217f0",
          "sha256": "e92789d1e7c7060f5d9c9a85eb283c2ea07c2329d3723abd4b4af848ba34a072",
          "sha1": "84692601e1b4b6335f4c453f80450791c979d87b",
          "md5": "5a3108cc910018b6ddd1105ca70ff100"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-web-6.4.4-sources.jar",
          "url": "spring-security-web-6.4.4-sources.jar",
          "size": 828041,
          "sha512": "1700d37580f1025f4b411b84b922f6ffa29860c53523d3a26156af91832316c895525b9884cd35dba4f6f8d2ada28118d536c0bd1778d6e53a38072916bae962",
          "sha256": "27935cdbb56319666ea26dd2a4bc56563546be332683c01d588937d4978bd6a0",
          "sha1": "08960e9d5a28269e1b010cd94934c740f0f47ab0",
          "md5": "bf79fa0b0396f1cc4343334d05dca0a8"
        }
      ]
    }
  ]
}
